FROM --platform=linux/amd64 golang:alpine

WORKDIR /app

COPY *.json ./
# COPY certs ./certs
ENV GO111MODULE=on
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
CMD ["go", "run", "envoy-control"]