version: "3.8"

services:
  app:
    build: .
    image: myswarmdns
    ports:
      - 53:53/udp
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role == manager]